apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: foo
      labels:
        env: test
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: foo
              value: poo
  replicas: 3
