apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: foo
      labels:
        env: test
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: foo
              value: poo
